# Generated by Django 6.0 on 2026-01-21 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginausuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('idexperiencialaboral', models.AutoField(primary_key=True, serialize=False)),
                ('cargodesempenado', models.CharField(max_length=100)),
                ('nombrempresa', models.CharField(max_length=50)),
                ('lugarempresa', models.CharField(max_length=50)),
                ('emailempresa', models.CharField(blank=True, max_length=100, null=True)),
                ('sitiowebempresa', models.CharField(blank=True, max_length=100, null=True)),
                ('nombrecontactoempresarial', models.CharField(blank=True, max_length=100, null=True)),
                ('telefonocontactoempresarial', models.CharField(blank=True, max_length=60, null=True)),
                ('fechainiciogestion', models.DateField()),
                ('fechafingestion', models.DateField(blank=True, null=True)),
                ('descripcionfunciones', models.CharField(max_length=100)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('rutacertificado', models.CharField(blank=True, max_length=100, null=True)),
                ('idperfilconqueestaactivo', models.ForeignKey(db_column='idperfilconqueestaactivo', on_delete=django.db.models.deletion.CASCADE, to='paginausuario.datospersonales')),
            ],
            options={
                'db_table': 'experiencialaboral',
            },
        ),
    ]
