# Generated by Django 6.0 on 2026-01-21 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginausuario', '0002_experiencialaboral'),
    ]

    operations = [
    ]
