# Generated by Django 6.0 on 2026-01-21 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginausuario', '0003_auto_20260121_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoRealizado',
            fields=[
                ('idcursorealizado', models.AutoField(primary_key=True, serialize=False)),
                ('nombrecurso', models.CharField(max_length=100)),
                ('fechainicio', models.DateField()),
                ('fechafin', models.DateField(blank=True, null=True)),
                ('totalhoras', models.IntegerField()),
                ('descripcioncurso', models.CharField(max_length=100)),
                ('entidadpatrocinadora', models.CharField(max_length=100)),
                ('nombrecontactoauspicia', models.CharField(blank=True, max_length=100, null=True)),
                ('telefonocontactoauspicia', models.CharField(blank=True, max_length=60, null=True)),
                ('emailempresapatrocinadora', models.CharField(blank=True, max_length=60, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('rutacertificado', models.CharField(blank=True, max_length=100, null=True)),
                ('idperfilconqueestaactivo', models.ForeignKey(db_column='idperfilconqueestaactivo', on_delete=django.db.models.deletion.CASCADE, to='paginausuario.datospersonales')),
            ],
            options={
                'db_table': 'cursosrealizados',
            },
        ),
        migrations.CreateModel(
            name='Reconocimiento',
            fields=[
                ('idreconocimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tiporeconocimiento', models.CharField(choices=[('Académico', 'Académico'), ('Público', 'Público'), ('Privado', 'Privado')], max_length=100)),
                ('fechareconocimiento', models.DateField()),
                ('descripcionreconocimiento', models.CharField(max_length=100)),
                ('entidadpatrocinadora', models.CharField(max_length=100)),
                ('nombrecontactoauspicia', models.CharField(blank=True, max_length=100, null=True)),
                ('telefonocontactoauspicia', models.CharField(blank=True, max_length=60, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('rutacertificado', models.CharField(blank=True, max_length=100, null=True)),
                ('idperfilconqueestaactivo', models.ForeignKey(db_column='idperfilconqueestaactivo', on_delete=django.db.models.deletion.CASCADE, to='paginausuario.datospersonales')),
            ],
            options={
                'db_table': 'reconocimientos',
            },
        ),
    ]
