# Generated by Django 6.0 on 2026-01-21 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginausuario', '0005_productoacademico'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoLaboral',
            fields=[
                ('idproductoslaborales', models.AutoField(primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(max_length=100)),
                ('fechaproducto', models.DateField()),
                ('descripcion', models.CharField(max_length=100)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('idperfilconqueestaactivo', models.ForeignKey(db_column='idperfilconqueestaactivo', on_delete=django.db.models.deletion.CASCADE, to='paginausuario.datospersonales')),
            ],
            options={
                'db_table': 'productoslaborales',
            },
        ),
    ]
