# Generated by Django 6.0 on 2026-01-21 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginausuario', '0006_productolaboral'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaGarage',
            fields=[
                ('idventagarage', models.AutoField(primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(max_length=100)),
                ('estadoproducto', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular')], max_length=40)),
                ('descripcion', models.CharField(max_length=100)),
                ('valordelbien', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('idperfilconqueestaactivo', models.ForeignKey(db_column='idperfilconqueestaactivo', on_delete=django.db.models.deletion.CASCADE, to='paginausuario.datospersonales')),
            ],
            options={
                'db_table': 'ventagarage',
            },
        ),
    ]
