# Generated by Django 6.0 on 2026-01-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginausuario', '0006_productolaboral'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
    ]
