# Generated by Django 6.0 on 2026-02-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginausuario', '0009_alter_cursorealizado_activarparaqueseveaenfront_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='descripcionperfil',
            field=models.CharField(max_length=200),
        ),
    ]
