# Generated by assistant: add imagen field to VentaGarage
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('paginausuario', '0010_alter_datospersonales_descripcionperfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventagarage',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='ventas_garage/'),
        ),
    ]
